// let arr = [5, 10, 'rahul', true, undefined, null, [1,2,3,4,5]]
// // console.log(arr[6][3])
// // console.log(arr.length)
// let name = 'kushagar'

// // for (let i = 0; i<name.length; i++){
// //     console.log(name[i])
// // }

// // for (let i of arr){
// //     console.log(i)
// // }

// for (let n of name){
//     console.log(n)
// }

// let num = [1,2,3,4,5]
// console.log(num)

// //push
// num.push(6)
// console.log(num)
// //push allways return length of the array!!

// //pop
// num.pop()
// console.log(num)

// //shift
// num.shift()
// console.log(num)

// //unshift
// num.unshift(1)
// console.log(num)


//slice
// let num1 = num.slice(1,4)
// console.log(num1)

// //includes
// console.log(num.includes(5))

// //sort 
// let nm = ['G', 'U', 'n']
// console.log(nm.sort())


//sort((a,b)=> a-b)
// let num = [1, 12, 12, 10, 134]
// console.log(num.sort((a,b)=> a-b))
// console.log(num.sort((a,b)=>b-a))
